name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs: 
  bucket: 
    description: ;'The s3 bucket name. mann-gha-custom-action-hosting'
    required: true
  bucket-region: 
    description: 'The region of the s3 buckets.'
    required: false
    default: 'ap-southeast-2'
  dist-folder:
    description: 'The folder container the deployable files.'
    required: true
runs: 
  using: 'node16'
  main: 'main.js'